name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Fetch required Go modules
      run:  go mod download
      
    - name: Build
      run: go build -v ./...

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-port: 27017
        mongodb-db: golang
        mongodb-username: mongo 
        mongodb-password: mongo
        
    - name: Test
      run: go test -v ./...